apiVersion: v1
kind: Pod
metadata:
  name: myapp8
  namespace: mynewtg
  labels:
    env: prod
spec:
  nodeName: wn2.tg.com
  volumes:
   - name: myvol1
     hostPath:
      path: /opt/website1
      type: Directory
  containers:
   - name: c1
     image: cdtsbikaner/devops150624:nodejsv1
     volumeMounts:
      - name: myvol1
        mountPath: /usr/share/nginx/html
        readOnly:  true

