# ClusterRole YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harman-clusterrole
rules:
  - apiGroups: ["*"]
    resources: ["pods", "services", "deployments", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

---
# ClusterRoleBinding YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harman-clusterrolebinding
roleRef:
  name: harman-clusterrole
  kind: ClusterRole
subjects:
  - kind: User
    name: harman
    apiGroup: rbac.authorization.k8s.io