apiVersion: v1
kind: Service
metadata:
  name: mynpservice1
  namespace: mynewtg
spec: 
  type: NodePort
  selector:
    env:  prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
