apiVersion: v1
kind: Pod
metadata:
  name: myapp6
  namespace: mynewtg
  labels:
    env: prod
spec:
  nodeName: wn1.tg.com
  volumes:
    - name: myvol1
      hostPath:
       path: /opt/tgbackup
       type: Directory
  containers:
    - name: c1
      image: cdtsbikaner/devops150624:nodejsv1
      volumeMounts:
       - name: myvol1
         mountPath: /usr/share/nginx/html
         readOnly: true
