apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-replicaset-autoscaler
  namespace: mynewtg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: my-replicaset
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Target CPU utilization

