apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    env: prod
  name: mysql-withsecret
  namespace: mynewtg
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mysql
      env: prod
  template:
    metadata:
      labels:
        app: mysql
        env: prod
    spec:
      containers:
      - image: mysql:5.7
        name: mysql-withsecret
        ports:
         - containerPort: 3306
        env: 
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
            secretKeyRef:
             name: mydbinfo
             key: password  
      tolerations:
      - key: high
        operator: Equal
        value: intensive
        effect: NoSchedule
